# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bundle and draft release

on:
  push:
    branches: [ main ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
    # Drafts your next Release notes as Pull Requests are merged into "main"
    - name: Draft release notes
      id: draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Map a step output to a job output
    outputs:
      tag_name: ${{ steps.draft.outputs.tag_name }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7]
    needs: [update_release_draft]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upload artefact to release
      run: |
        echo ${{ env.VERSION }} >> ./GiantBomb.bundle/Contents/VERSION
        zip -r GiantBomb.bundle.zip ./GiantBomb.bundle
        gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ needs.update_release_draft.outputs.tag_name }}
        FILES: GiantBomb.bundle.zip
